index:
  nav:
    features: 特性
    resources: 资料
    facilities: 周边
practice:
  data:
    title: 数据
    0: 什么东西可以保存在 data 里？
    1: 什么东西不要保存在 data 里？
    2: data bind 时的 auto camel
  tpl:
    title: 视图模板
    0: 如何遍历一个对象？
    1: 数组深层更新如何触发视图更新？
    2: 如何实现元素的显示/隐藏？
  msg:
    title: 组件间通信
    0: 父组件如何更新子组件？
    1: 子组件如何通知父组件？
    2: 子组件与更高层的组件如何通信？
    3: 动态子组件如何传递消息给父组件?
  component:
    title: 组件管理
    0: 我们可以操作 DOM 吗？
    1: 如何处理绝对定位组件的 DOM？
  route:
    title: 路由管理
    0: 如何使用 san-router 建立一个单页应用的后台系统？
  state:
    title: 应用状态管理
    0: 如何使用 san-store 实现后台系统的状态管理？
  faq:
    0: Q&A集锦